server:
  port: 8080

foodtec:
  inventory:
    service:
      url: http://localhost:8081/internal/food-items/
      key: internal-secret-key

logging:
  level:
    com.product.verification.gateway: DEBUG
